find_path(TAGLIB_INCLUDE_DIR taglib/tag.h)
find_library(TAGLIB_LIBRARY NAMES tag taglib)

if(TAGLIB_INCLUDE_DIR AND TAGLIB_LIBRARY)
  set(TAGLIB_FOUND TRUE)
  set(TAGLIB_LIBRARIES ${TAGLIB_LIBRARY})
  set(TAGLIB_INCLUDE_DIRS ${TAGLIB_INCLUDE_DIR})
else()
  set(TAGLIB_FOUND FALSE)
endif()

mark_as_advanced(TAGLIB_INCLUDE_DIR TAGLIB_LIBRARY)
